export const menus = [
  {
    menu_aid: 1,
    menu_title: "2pc Chickenjoy",
    menu_category: "Chicken",
    menu_price: "200",
    menu_image: "chicken-1.webp",
  },
  {
    menu_aid: 2,
    menu_title: "2pc Chickenjoy",
    menu_category: "Chicken",
    menu_price: "270",
    menu_image: "chicken-2.webp",
  },
  {
    menu_aid: 3,
    menu_title: "2x Fries Bucket Chickenjoy",
    menu_category: "Chicken",
    menu_price: "270",
    menu_image: "chicken-3.webp",
  },
  {
    menu_aid: 4,
    menu_title: "Family Spaghetti",
    menu_category: "Chicken",
    menu_price: "450",
    menu_image: "chicken-4.webp",
  },
  {
    menu_aid: 5,
    menu_title: "1x Fries Bucket Chickenjoy",
    menu_category: "Chicken",
    menu_price: "200",
    menu_image: "chicken-5.webp",
  },
  {
    menu_aid: 6,
    menu_title: "8pc Bucket Chickenjoy",
    menu_category: "Chicken",
    menu_price: "200",
    menu_image: "chicken-6.webp",
  },
  {
    menu_aid: 7,
    menu_title: "Chicken Burger w/ Fries",
    menu_category: "Value Meal",
    menu_price: "350",
    menu_image: "value-meal-1.webp",
  },
  {
    menu_aid: 8,
    menu_title: "Cheezee Chicken Burger ",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-2.webp",
  },
  {
    menu_aid: 9,
    menu_title: "2pc Chicken w/ Peach Mango ",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-3.webp",
  },
  {
    menu_aid: 10,
    menu_title: "8pc Bucket Chicken w/ 3Peach Mango ",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-4.webp",
  },
  {
    menu_aid: 11,
    menu_title: "8pc Bucket Chicken w/ 3Peach Mango ",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-5.webp",
  },
  {
    menu_aid: 12,
    menu_title: "Yum Burger ",
    menu_category: "Burger",
    menu_price: "100",
    menu_image: "burger-1.webp",
  },
  {
    menu_aid: 13,
    menu_title: "Yum Burger w/ Fries",
    menu_category: "Burger",
    menu_price: "120",
    menu_image: "burger-2.webp",
    },
  {
    menu_aid: 23,
    menu_title: "Cheese Burger",
    menu_category: "Burger",
    menu_price: "120",
    menu_image: "burger-3.webp",
    },
  {
    menu_aid: 24,
    menu_title: "Cheese Burger w/ Fries",
    menu_category: "Burger",
    menu_price: "150",
    menu_image: "burger-4.webp",
    },
  {
    menu_aid: 25,
    menu_title: "Double Patty",
    menu_category: "Burger",
    menu_price: "250",
    menu_image: "burger-5.webp",
    },
  {
    menu_aid: 26,
    menu_title: "Burger Combo",
    menu_category: "Burger",
    menu_price: "300",
    menu_image: "burger-6.webp",
    },
  {
    menu_aid: 27,
    menu_title: "Burger Deluxe",
    menu_category: "Burger",
    menu_price: "350",
    menu_image: "burger-7.webp",
    },
  {
    menu_aid: 28,
    menu_title: "Burger Deluxe w/ Fries",
    menu_category: "Burger",
    menu_price: "350",
    menu_image: "burger-7.webp",
    },
  
  {
    menu_aid: 14,
    menu_title: "Peach Mango Pie",
    menu_category: "Dessert",
    menu_price: "60",
    menu_image: "dessert-1.webp",
  },
  {
    menu_aid: 15,
    menu_title: "Ube Pie",
    menu_category: "Dessert",
    menu_price: "60",
    menu_image: "dessert-2.webp",
    },
  {
    menu_aid: 29,
    menu_title: "2pc Peach Mango Pie",
    menu_category: "Dessert",
    menu_price: "100",
    menu_image: "dessert-3.webp",
    },
  {
    menu_aid: 30,
    menu_title: "Pineapple Juice",
    menu_category: "Dessert",
    menu_price: "100",
    menu_image: "dessert-4.webp",
    },
  {
    menu_aid: 31,
    menu_title: "Coke",
    menu_category: "Dessert",
    menu_price: "50",
    menu_image: "dessert-5.webp",
    },
  
  {
    menu_aid: 16,
    menu_title: "Palabok",
    menu_category: "Palabok",
    menu_price: "100",
    menu_image: "palabok-1.webp",
  },
  {
    menu_aid: 17,
    menu_title: "Palabok w/ Drinks",
    menu_category: "Palabok",
    menu_price: "90",
    menu_image: "palabok-2.webp",
    },
  {
    menu_aid: 32,
    menu_title: "Family Palabok",
    menu_category: "Palabok",
    menu_price: "200",
    menu_image: "palabok-3.webp",
    },
  {
    menu_aid: 33,
    menu_title: "Palabok Grande",
    menu_category: "Palabok",
    menu_price: "500",
    menu_image: "palabok-4.webp",
    },
  
  {
    menu_aid: 18,
    menu_title: "Regular Fries",
    menu_category: "Sides",
    menu_price: "40",
    menu_image: "sides-1.webp",
  },
  {
    menu_aid: 19,
    menu_title: "Mashed Potato",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-2.webp",
    },
  {
    menu_aid: 34,
    menu_title: "Spaghetti",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-3.webp",
    },
  {
    menu_aid: 35,
    menu_title: "Adobo Rice",
    menu_category: "Sides",
    menu_price: "50",
    menu_image: "sides-4.webp",
    },
  {
    menu_aid: 36,
    menu_title: "Spaghetti sa sulyaw",
    menu_category: "Sides",
    menu_price: "90",
    menu_image: "sides-5.webp",
    },
  
  {
    menu_aid: 19,
    menu_title: "Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "100",
    menu_image: "spag-1.webp",
  },
  {
    menu_aid: 20,
    menu_title: "Spaghetti w/ Chicken",
    menu_category: "Spaghetti",
    menu_price: "150",
    menu_image: "spag-2.webp",
    },
  
  {
    menu_aid: 37,
    menu_title: "Family Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "150",
    menu_image: "spag-3.webp",
    },
  
  {
    menu_aid: 21,
    menu_title: "Burger Steak",
    menu_category: "Steak",
    menu_price: "100",
    menu_image: "steak-1.webp",
  },
  {
    menu_aid: 22,
    menu_title: "6pc Burger Steak",
    menu_category: "Steak",
    menu_price: "300",
    menu_image: "steak-2.webp",
  },
  {
    menu_aid: 38,
    menu_title: "Wombo Combo",
    menu_category: "Steak",
    menu_price: "700",
    menu_image: "steak-3.webp",
  },
];
